let nextButton = document.getElementById("next")
let prevButton = document.getElementById('prev')
let carousel = document.querySelector(".carousel")
let listHTML = document.querySelector('.carousel .list')
let seeMoreButtons = document.querySelectorAll('seeMore')
let backButton = document.getElementById("back")